/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myJava.code.challenges;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestTreeLibrary {

    @Test void testBinaryNode_CanInstantiate() {
        int expectedValue = 11;
        MyBinaryNode sut = new MyBinaryNode(expectedValue);
        assertNotNull(sut);
        assertEquals(expectedValue, sut.getValue());
    }

    @Test void testBinaryNode_GetterSetters() {
        MyBinaryNode sut = new MyBinaryNode(11);
        MyBinaryNode leftSut = new MyBinaryNode(10);
        sut.setLeft(leftSut);
        assertEquals(leftSut, sut.getLeft());
        assertEquals(sut.getLeft().getValue(), leftSut.getValue());
        MyBinaryNode rightSut = new MyBinaryNode(12);
        sut.setRight(rightSut);
        assertEquals(rightSut, sut.getRight());
        assertEquals(sut.getRight().getValue(), rightSut.getValue());
    }

    @Test void testBinaryTree_CanInstantiateEmpty() {
        MyBinaryTree sut = new MyBinaryTree();
        assertNotNull(sut);
        assertNull(sut.getRoot());
    }

    @Test void testBinaryTree_CanInstantiateWithValue() {
        MyBinaryNode node = new MyBinaryNode(11);
        MyBinaryTree sut = new MyBinaryTree(node);
        assertNotNull(sut);
        assertEquals(node, sut.getRoot());
    }

    @Test void testBST_CanInstantiateEmpty() {
        MyBinaryNode node = new MyBinaryNode(11);
        MyBST sut = new MyBST(node);
        assertNotNull(sut);
        assertEquals(node, sut.getRoot());
    }

    @Test void testBinaryTree_PreOrderExpectedResults() {
        MyBinaryNode firstRoot = new MyBinaryNode(1);
        MyBinaryNode secondLeft = new MyBinaryNode(2);
        MyBinaryNode secondRight = new MyBinaryNode(3);
        MyBinaryNode thirdLeftLeft = new MyBinaryNode(4);
        MyBinaryNode thirdLeftRight = new MyBinaryNode(5);
        MyBinaryNode thirdRightLeft = new MyBinaryNode(6);
        MyBinaryNode thirdRightRight = new MyBinaryNode(7);

        MyBinaryTree sut = new MyBinaryTree(firstRoot);
        var actualRoot = sut.getRoot();
        assertEquals(firstRoot, actualRoot);

        sut.resetStorageArray();
        sut.preOrder(firstRoot);
        assertEquals("[ 1 ]", sut.getStorageArray());

        String expectedPreOrderArray = "[ 1, 2, 4, 5, 3, 6, 7 ]";

        firstRoot.setLeft(secondLeft);
        firstRoot.setRight(secondRight);
        secondLeft.setLeft(thirdLeftLeft);
        secondLeft.setRight(thirdLeftRight);
        secondRight.setLeft(thirdRightLeft);
        secondRight.setRight(thirdRightRight);

        sut.resetStorageArray();
        sut.preOrder(sut.getRoot());
        assertEquals(expectedPreOrderArray, sut.getStorageArray());
    }

    @Test void testBinaryTree_GetStringOfArray() {
        MyBinaryTree sut = new MyBinaryTree();
        assertEquals("[]", sut.getStorageArray());

        int expectedValue = 11;
        String expectedResult = String.format("[ %1$s ]", expectedValue);

        sut.resetStorageArray();
        sut.addItemToStorageArray(expectedValue);
        assertEquals(expectedResult, sut.getStorageArray());
    }
}
